### ISSUE TITLE
Feature Request: 在课表界面提供切换周数功能

### ISSUE THREAD

**Issue by gbccccc** [WheretoSleepinNJU/NJU-Class-Shedule-Flutter#23]
现在的版本要切教学周数似乎只能进入设置界面，通过一个 Select 进行切换。这个在一些场景下非常不友好：比如我有一节课只在某一周上课，但又不知道具体是那一周，这时候如果想查找这门课的上课时间就会非常麻烦；又比如我有一个长期计划要安排，这时候我希望查看之后若干周的课表提前安排计划，这种场景下切换教学周数的行为往往会很频繁，且是反复的来回切换。

如果在课表界面就能切换（手势滑动或按钮均可），似乎会对用户更友好一点。

（新用户，如果是我有对已有功能有误解还请原谅 QAQ）

**Comment by baoheipojis** [comment]
似乎已经有这个功能了，具体做法是点击主界面周数的数字，下面就会出现一个滑动条，可以选择任意周数。
不过手势左右滑动确实更方便一点

**Comment by gbccccc** [comment]
> 似乎已经有这个功能了，具体做法是点击主界面周数的数字，下面就会出现一个滑动条，可以选择任意周数。 不过手势左右滑动确实更方便一点

啊这样，那是我之前没发现，打扰各位了orz
